GLOBAL:
  random_state: 42
  test_size: 0.2
  results_dir: ./results
  cache_dir: ./cache

DATASETS:
  cybersecurity:
    path: ./data/cyber.csv
    imp_max_iter: 30
    feature_extractor: sentence_transformer
    pca_components: 100

FEATURES:
  cybersecurity:
    nominal_features: ["colA", "colB"]
    text_features: ["text"]

MODEL_CONFIGS:
  lr:
    penalty: "l2"
    solver: "saga"
    max_iter: 10000

DATA_PREP_CONFIG:
  iter_imp:
    max_iter: 30
  simp_imp:
    strategy: "most_frequent"
  OHE:
    handle_unknown: "ignore"
    drop: "if_binary"
